title: Declan's learning nook
description: Welcome!
remote_theme: "jekyll/minima@1e8a445"
collections:
  misc:
    output: true
  q_and_a:
    output: true       # generate HTML pages for each item
    permalink: /q-and-a/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional: default image for posts/pages without one
defaults:
  - scope: {path: ""}                  # whole site
    values:
      image: /favicon.png
  - scope:
      path: ""            # any path
      type: q_and_a       # only documents in the q_and_a collection
    values:
      image: /assets/thumbnails/thinking_monkey.png
      thumbnail: /assets/thumbnails/thinking_monkey.png


markdown: kramdown

kramdown:
  toc_levels: 2..6   # which heading levels to include (optional, but nice)